/*
Длина  Формат 
13  СС РРР ГГГ ППП КК 
17  СС РРР ГГГ ППП УУУУ КК 
19  СС РРР ГГГ ППП УУУУ ДДДД 



Код  Описание 
СС  код субъекта Российской Федерации (региона) 
РРР  код района 
ГГГ  код города 
ППП  код населенного пункта 
УУУУ  код улицы 
ДДДД  порядковый номер позиции классификатора с обозначениями домов 
КК  код актуальности наименования 
*/

ALTER TABLE [dbo].[KLADR150817_KLADR] REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = PAGE)
GO
ALTER TABLE [dbo].[KLADR150817_KLADR] ALTER COLUMN [CODE] [varchar](13) COLLATE Cyrillic_General_BIN NOT NULL
GO
CREATE CLUSTERED INDEX [IX_KLADR150817_KLADR#NAME] ON [dbo].[KLADR150817_KLADR] 
(
	[NAME] ASC,
	[SOCR] ASC
)
WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_KLADR150817_KLADR#INDEX] ON [dbo].[KLADR150817_KLADR] 
(
	[INDEX] ASC
)
INCLUDE([CODE], [NAME])
WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO


ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [@CODE:1-2] AS (left([CODE],(2)))
ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [@CODE:3-5] AS (substring([CODE],(3),(3)))
ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [@CODE:6-8] AS (substring([CODE],(6),(3)))
ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [@CODE:9-11] AS (substring([CODE],(9),(3)))
ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [@CODE:12-13] AS (substring([CODE],(12),(2)))
ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [LEVEL] AS
(
    CASE
      WHEN SubString([Code], 3, 9) = '000000000' THEN 1
      WHEN SubString([Code], 3, 3) <> '000' AND SubString([Code], 6, 6) = '000000' THEN 2
      WHEN SubString([Code], 6, 3) <> '000' AND SubString([Code], 9, 3) = '000' THEN 3
      ELSE 4
    END
)
ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [@CODE] AS
(
    CASE
      WHEN SubString([Code], 3, 9) = '000000000' THEN LEFT([Code], 2)
      WHEN SubString([Code], 3, 3) <> '000' AND SubString([Code], 6, 6) = '000000' THEN LEFT([Code], 5)
      WHEN SubString([Code], 6, 3) <> '000' AND SubString([Code], 9, 3) = '000' THEN LEFT([Code], 8)
      ELSE LEFT([Code], 11)
    END
)
ALTER TABLE [dbo].[KLADR150817_KLADR] ADD [@CODE:STATUS]  AS (substring([CODE],(12),(2)))
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_KLADR150817_KLADR#@CODE] ON [dbo].[KLADR150817_KLADR] 
(
	[@CODE] ASC,
	[@CODE:STATUS] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO

ALTER TABLE [dbo].[KLADR150817_ALTNAMES] REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = PAGE)
GO
ALTER TABLE [dbo].[KLADR150817_ALTNAMES] ALTER COLUMN [OLDCODE] [varchar](17) COLLATE Cyrillic_General_BIN NOT NULL
ALTER TABLE [dbo].[KLADR150817_ALTNAMES] ALTER COLUMN [NEWCODE] [varchar](17) COLLATE Cyrillic_General_BIN NOT NULL
GO
CREATE CLUSTERED INDEX [IX_KLADR150817_ALTNAMES#OLDCODE] ON [dbo].[KLADR150817_ALTNAMES] 
(
	[OLDCODE] ASC,
	[LEVEL] ASC
)
WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO

-----------

ALTER TABLE [dbo].[KLADR150817_STREET] REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = PAGE)
GO
ALTER TABLE [dbo].[KLADR150817_STREET] ALTER COLUMN [CODE] [varchar](17) COLLATE Cyrillic_General_BIN NOT NULL
GO
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:1-2]  AS (left([CODE],(2)))
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:3-5]  AS (substring([CODE],(3),(3)))
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:6-8]  AS (substring([CODE],(6),(3)))
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:9-11]  AS (substring([CODE],(9),(3)))
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:12-15]  AS (substring([CODE],(12),(4)))
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:16-17]  AS (substring([CODE],(16),(2)))
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:PARENT] AS (left([CODE],(11)))
ALTER TABLE [dbo].[KLADR150817_STREET]  ADD [@CODE:STATUS] AS (substring([CODE],(16),(2)))

GO

CREATE CLUSTERED INDEX [IX_KLADR150817_STREET#NAME] ON [dbo].[KLADR150817_STREET]
(
	[NAME] ASC,
	[SOCR] ASC
)
WITH (STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_KLADR150817_STREET#PARENT] ON [dbo].[KLADR150817_STREET] 
(
	[@CODE:PARENT] ASC,
	[NAME] ASC,
	[SOCR] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO

---------------
ALTER TABLE [dbo].[KLADR150817_doma] REBUILD PARTITION = ALL WITH (DATA_COMPRESSION = PAGE)
GO
ALTER TABLE [dbo].[KLADR150817_doma] ALTER COLUMN [CODE] [varchar](19) COLLATE Cyrillic_General_BIN NOT NULL
GO
ALTER TABLE [dbo].[KLADR150817_doma]  ADD [@CODE:1-15]  AS (left([CODE],(15)))
GO
CREATE CLUSTERED INDEX [IX_dbo.KLADR:Doma#CODE PARENT] ON [dbo].[KLADR150817_doma] 
(
	[@CODE:1-15] ASC
)
WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = ON, ALLOW_ROW_LOCKS  = OFF, ALLOW_PAGE_LOCKS  = ON, DATA_COMPRESSION = PAGE) ON [PRIMARY]
GO


DROP SYNONYM [dbo].[KLADR:Base]
GO
IF OBJECT_ID('[dbo].[KLADR:Base]') IS NULL
  CREATE SYNONYM [dbo].[KLADR:Base] FOR [dbo].[KLADR150817_KLADR]
GO
DROP SYNONYM [dbo].[KLADR:AltNames]
GO
IF OBJECT_ID('[dbo].[KLADR:AltNames]') IS NULL
  CREATE SYNONYM [dbo].[KLADR:AltNames] FOR [dbo].[KLADR150817_ALTNAMES]
GO
DROP SYNONYM [dbo].[KLADR:Streets]
GO
IF OBJECT_ID('[dbo].[KLADR:Streets]') IS NULL
  CREATE SYNONYM [dbo].[KLADR:Streets] FOR [dbo].[KLADR150817_Street]
GO
DROP SYNONYM [dbo].[KLADR:Doma]
GO
IF OBJECT_ID('[dbo].[KLADR:Doma]') IS NULL
  CREATE SYNONYM [dbo].[KLADR:Doma] FOR [dbo].[KLADR150817_doma]
GO
