--F:\SVUData
--H:\SVULogs

RESTORE DATABASE [BackOffice] 
  FROM DISK = N'\\PUCHKOV\BackUp\BackOffice.bak' 
  WITH FILE = 1,
  MOVE N'Data' TO N'C:\MS SQL 2014 CTP2\Data\BackOffice.mdf',
  MOVE N'Log' TO N'C:\MS SQL 2014 CTP2\Data\BackOffice.ldf',
  NOUNLOAD,
  STATS = 10

EXEC [BackOffice].dbo.sp_changedbowner @loginame = N'sa', @map = false

ALTER DATABASE [BackOffice] SET
  ANSI_NULLS ON,
  ANSI_NULL_DEFAULT ON,
  ANSI_PADDING ON,
  ANSI_WARNINGS ON,
  ARITHABORT ON,
  CONCAT_NULL_YIELDS_NULL ON,
  QUOTED_IDENTIFIER ON,
  CURSOR_DEFAULT LOCAL,
  READ_COMMITTED_SNAPSHOT ON,
  DB_CHAINING ON, 
  TRUSTWORTHY ON
  WITH ROLLBACK IMMEDIATE

ALTER DATABASE [BackOffice] SET NEW_BROKER WITH ROLLBACK IMMEDIATE

ALTER DATABASE [BackOffice] SET ENABLE_BROKER WITH ROLLBACK IMMEDIATE
